#!/usr/bin/env bash
# Скрипт, запускаемый модулем pam_script.so, для проверки принадлежности подключающегося пользователя группе
#"admin", и если пользователь не в группе admin и выходной день (5 или 6-ой день недели) то  выход из скрипта. #Т.е прерываем работу и пользователь не проходит authentication. Если в группе, то подключаться можно всегда
      echo $PAM_USER >> /root/test
      if [[ ! $(grep $PAM_USER /etc/group | grep 'admin') ]]
          then
              if [[ $(date +%u) -ge 5 ]]
                  then
                      echo "Сегодня выходной нечего тут делать $(date +%u)"
                      exit 1
                  else
                      exit 0
              fi
          else
              exit 0

fi
